name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21
          cache: true
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Add webp
        run: sudo apt-get install libwebp-dev
      - name: Build Go binary
        run: go build -o bin/ -v ./...
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag erans/thumbla --tag thumbla:$(date +%s)
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/thumbla
